// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPrr2F6hzTLNMC7ZmHWpJtgqF3rLXhR4',
    appId: '1:78196582552:web:d75115ba95abeb97fdc8ed',
    messagingSenderId: '78196582552',
    projectId: 'sitio-web-patitas',
    authDomain: 'sitio-web-patitas.firebaseapp.com',
    storageBucket: 'sitio-web-patitas.firebasestorage.app',
    measurementId: 'G-X9M5NQKQS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtuIKXqjR8U4nS-hbjFkqBVOsaH9UZnWk',
    appId: '1:78196582552:android:1cd64a62d4271614fdc8ed',
    messagingSenderId: '78196582552',
    projectId: 'sitio-web-patitas',
    storageBucket: 'sitio-web-patitas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmOlD4VSi9-qahaGcN-CLANkI543oWPfE',
    appId: '1:78196582552:ios:6217bbcce4e83095fdc8ed',
    messagingSenderId: '78196582552',
    projectId: 'sitio-web-patitas',
    storageBucket: 'sitio-web-patitas.firebasestorage.app',
    iosBundleId: 'com.example.patitasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmOlD4VSi9-qahaGcN-CLANkI543oWPfE',
    appId: '1:78196582552:ios:6217bbcce4e83095fdc8ed',
    messagingSenderId: '78196582552',
    projectId: 'sitio-web-patitas',
    storageBucket: 'sitio-web-patitas.firebasestorage.app',
    iosBundleId: 'com.example.patitasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALPrr2F6hzTLNMC7ZmHWpJtgqF3rLXhR4',
    appId: '1:78196582552:web:bef8a00717bf8890fdc8ed',
    messagingSenderId: '78196582552',
    projectId: 'sitio-web-patitas',
    authDomain: 'sitio-web-patitas.firebaseapp.com',
    storageBucket: 'sitio-web-patitas.firebasestorage.app',
    measurementId: 'G-YMLBMYDELW',
  );
}
